In [1]:
import numpy as np
data = np.array([[1], [2], [3]])

In [2]:
data.ndim

2

In [3]:
data

array([[1],
       [2],
       [3]])

In [4]:
a=np.squeeze(data)

In [5]:
a

array([1, 2, 3])

In [6]:
a.ndim

1

In [7]:
data

array([[1],
       [2],
       [3]])

In [8]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [9]:
a = np.array([[1, 2], [3, 4]])

In [10]:
a

array([[1, 2],
       [3, 4]])

In [11]:
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [12]:
a

array([[1, 2],
       [3, 4]])

In [13]:
np.repeat(a,2,axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [14]:
np.repeat(a,2,axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [15]:
data

array([[1],
       [2],
       [3]])

In [16]:
np.roll(data,1)

array([[3],
       [1],
       [2]])

In [17]:
np.roll(data,-1)

array([[2],
       [3],
       [1]])

In [18]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
a = np.array([[1, 2], [3, 4],[5,6]])

In [20]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
np.roll(a,1)

array([[6, 1],
       [2, 3],
       [4, 5]])

In [22]:
#binary operation on array

In [23]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [24]:
arr1

array([[1, 4, 7, 3],
       [3, 5, 5, 4],
       [4, 6, 5, 7]])

In [25]:
arr2

array([[1, 4, 3, 3],
       [7, 2, 8, 5],
       [3, 3, 6, 4]])

In [26]:
arr1+arr2

array([[ 2,  8, 10,  6],
       [10,  7, 13,  9],
       [ 7,  9, 11, 11]])

In [27]:
arr1*arr2

array([[ 1, 16, 21,  9],
       [21, 10, 40, 20],
       [12, 18, 30, 28]])

In [28]:
arr1/arr2

array([[1.        , 1.        , 2.33333333, 1.        ],
       [0.42857143, 2.5       , 0.625     , 0.8       ],
       [1.33333333, 2.        , 0.83333333, 1.75      ]])

In [29]:
arr1-arr2

array([[ 0,  0,  4,  0],
       [-4,  3, -3, -1],
       [ 1,  3, -1,  3]])

In [30]:
arr1**arr2

array([[     1,    256,    343,     27],
       [  2187,     25, 390625,   1024],
       [    64,    216,  15625,   2401]])

In [31]:
~arr1

array([[-2, -5, -8, -4],
       [-4, -6, -6, -5],
       [-5, -7, -6, -8]])

In [32]:
#numpy string function

In [33]:
arr=np.array(["pw","skills"])

In [34]:
arr

array(['pw', 'skills'], dtype='<U6')

In [35]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [36]:
np.char.lower(arr)

array(['pw', 'skills'], dtype='<U6')

In [37]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [38]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [39]:
#mathematical function 

In [40]:
arr1

array([[1, 4, 7, 3],
       [3, 5, 5, 4],
       [4, 6, 5, 7]])

In [41]:
np.sin(arr1)

array([[ 0.84147098, -0.7568025 ,  0.6569866 ,  0.14112001],
       [ 0.14112001, -0.95892427, -0.95892427, -0.7568025 ],
       [-0.7568025 , -0.2794155 , -0.95892427,  0.6569866 ]])

In [42]:
np.cos(arr1)

array([[ 0.54030231, -0.65364362,  0.75390225, -0.9899925 ],
       [-0.9899925 ,  0.28366219,  0.28366219, -0.65364362],
       [-0.65364362,  0.96017029,  0.28366219,  0.75390225]])

In [43]:
np.log10(arr1)

array([[0.        , 0.60205999, 0.84509804, 0.47712125],
       [0.47712125, 0.69897   , 0.69897   , 0.60205999],
       [0.60205999, 0.77815125, 0.69897   , 0.84509804]])

In [44]:
np.exp(arr1)

array([[   2.71828183,   54.59815003, 1096.63315843,   20.08553692],
       [  20.08553692,  148.4131591 ,  148.4131591 ,   54.59815003],
       [  54.59815003,  403.42879349,  148.4131591 , 1096.63315843]])

In [45]:
np.power(arr1,3)

array([[  1,  64, 343,  27],
       [ 27, 125, 125,  64],
       [ 64, 216, 125, 343]], dtype=int32)

In [46]:
np.mean(arr1)

4.5

In [47]:
np.max(arr1)

7

In [48]:
np.std(arr1)

1.6583123951777

In [49]:
np.var(arr1)

2.75

In [50]:
np.subtract(arr1,arr2)

array([[ 0,  0,  4,  0],
       [-4,  3, -3, -1],
       [ 1,  3, -1,  3]])

In [51]:
np.mod(arr1,arr2)

array([[0, 0, 1, 0],
       [3, 1, 5, 4],
       [1, 0, 5, 3]])

In [52]:
#sort search

In [53]:
arr=np.array([5,6,1,2])

In [60]:
a=np.sort(arr)

In [61]:
a

array([1, 2, 5, 6])

In [62]:
np.searchsorted(a,3)

2

In [57]:
arr1=np.array([0,1,2,3,0,4])
np.count_nonzero(arr1)

4

In [58]:
arr1>0

array([False,  True,  True,  True, False,  True])

In [65]:
np.extract(arr1>0,arr1)

array([1, 2, 3, 4])

In [59]:
np.where(arr1>0)

(array([1, 2, 3, 5], dtype=int64),)

In [64]:
arr1.byteswap()

array([       0, 16777216, 33554432, 50331648,        0, 67108864])

In [66]:
#matrix = 2darray

In [67]:
import numpy.matlib as nm

In [68]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [69]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [75]:
arr1=np.array([[2,3],[4,5]])
arr2=np.array([[6,7],[1,5]])

In [76]:
arr1

array([[2, 3],
       [4, 5]])

In [77]:
arr2

array([[6, 7],
       [1, 5]])

In [78]:
arr1 @ arr2

array([[15, 29],
       [29, 53]])

In [79]:
#7x + 5y -3z = 16
#3x - 5y + 2z = -8
#5x + 3y - 7z = 0

In [80]:
a=np.array([[7,5,-3],[3,-5,2],[5,3,-7]])

In [81]:
a

array([[ 7,  5, -3],
       [ 3, -5,  2],
       [ 5,  3, -7]])

In [82]:
b=np.array([16,-8,0])

In [83]:
b

array([16, -8,  0])

In [84]:
np.linalg.solve(a,b)

array([1., 3., 2.])

In [85]:
arr1

array([[2, 3],
       [4, 5]])

In [86]:
np.linalg.det(arr1)

-2.0

In [87]:
np.linalg.inv(arr1)

array([[-2.5,  1.5],
       [ 2. , -1. ]])