In [153]:
import numpy as np

In [2]:
arr=np.ones((3,4))

In [6]:
np.empty((3,4),int)

array([[7471172, 7733353, 7471205, 6357060],
       [6357108, 4521984, 4390982, 3670111],
       [3407921, 3997744,      49, 5177414]])

In [8]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [9]:
import pandas as pd

In [10]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [12]:
import random

In [16]:
random.choice((1,2,3,4,5,6))

6

In [18]:
random.choice('ajay')

'j'

In [20]:
random.randrange(1,10)

8

In [25]:
random.random() #between 0 to 1

0.7425202744559896

In [22]:
lis=[1,2,3,4,5]
random.shuffle(lis)

In [23]:
lis

[3, 4, 2, 1, 5]

In [24]:
random.uniform(7,14)

10.800386776010173

In [26]:
#random using numpi

In [28]:
np.random.rand(1)

array([0.28687025])

In [27]:
np.random.rand(2,3)

array([[0.47641047, 0.01155621, 0.62370333],
       [0.65419208, 0.1558284 , 0.38571379]])

In [29]:
np.random.randn(2,3)

array([[ 2.20520852,  0.14024495,  0.2441143 ],
       [-0.24019134,  0.21315336, -0.33852223]])

In [30]:
np.random.random_sample()

0.3068950309856211

In [38]:
arr=np.random.randint(1,5,size=(3,4))

In [39]:
arr

array([[1, 1, 4, 4],
       [2, 1, 2, 4],
       [4, 3, 3, 2]])

In [40]:
arr.size

12

In [41]:
arr.shape

(3, 4)

In [42]:
arr.ndim

2

In [43]:
arr.reshape(2,6)

array([[1, 1, 4, 4, 2, 1],
       [2, 4, 4, 3, 3, 2]])

In [44]:
arr.reshape(4,-1)

array([[1, 1, 4],
       [4, 2, 1],
       [2, 4, 4],
       [3, 3, 2]])

In [45]:
arr.reshape(4,-100)

array([[1, 1, 4],
       [4, 2, 1],
       [2, 4, 4],
       [3, 3, 2]])

In [46]:
arr.reshape(-1, 4)

array([[1, 1, 4, 4],
       [2, 1, 2, 4],
       [4, 3, 3, 2]])

In [47]:
arr.reshape(12, ).base

array([[1, 1, 4, 4],
       [2, 1, 2, 4],
       [4, 3, 3, 2]])

In [48]:
arr

array([[1, 1, 4, 4],
       [2, 1, 2, 4],
       [4, 3, 3, 2]])

In [49]:
arr.reshape(2, 2, 3)

array([[[1, 1, 4],
        [4, 2, 1]],

       [[2, 4, 4],
        [3, 3, 2]]])

In [50]:
arr.reshape(1, 2, 2, 3)

array([[[[1, 1, 4],
         [4, 2, 1]],

        [[2, 4, 4],
         [3, 3, 2]]]])

In [51]:
arr.reshape(4, 3, 1)

array([[[1],
        [1],
        [4]],

       [[4],
        [2],
        [1]],

       [[2],
        [4],
        [4]],

       [[3],
        [3],
        [2]]])

In [52]:
arr.reshape(1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3)

array([[[[[[[[[[[[1, 1, 4],
                 [4, 2, 1]],

                [[2, 4, 4],
                 [3, 3, 2]]]]]]]]]]]])

In [53]:
lis = [1, 2, 3, 4]
arr = np.array(lis)

In [54]:
arr

array([1, 2, 3, 4])

In [55]:
arr.ndim

1

In [56]:
arr2 = np.array([[2, 3], [4, 5]])
arr2

array([[2, 3],
       [4, 5]])

In [58]:
arr2.ndim

2

In [59]:
arr2 = np.zeros((3, 4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
arr2.ndim

2

In [62]:
arr3 = np.zeros((1, 3, 4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [63]:
arr3.ndim

3

In [64]:
arr3.shape

(1, 3, 4)

In [65]:
arr3 = np.zeros((3, 3, 4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [66]:
arr3.ndim

3

In [67]:
arr3.shape

(3, 3, 4)

In [68]:
arr1 = np.random.randint(1, 10, (5, 6))

In [69]:
arr1

array([[2, 3, 7, 7, 3, 4],
       [7, 7, 9, 1, 1, 1],
       [8, 3, 1, 9, 5, 2],
       [9, 2, 3, 9, 5, 5],
       [2, 8, 2, 4, 5, 6]])

In [70]:
arr1 > 5

array([[False, False,  True,  True, False, False],
       [ True,  True,  True, False, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [False,  True, False, False, False,  True]])

In [71]:
arr1[arr1 > 5]

array([7, 7, 7, 7, 9, 8, 9, 9, 9, 8, 6])

In [72]:
arr1[arr1 < 5]

array([2, 3, 3, 4, 1, 1, 1, 3, 1, 2, 2, 3, 2, 2, 4])

In [73]:
arr1

array([[2, 3, 7, 7, 3, 4],
       [7, 7, 9, 1, 1, 1],
       [8, 3, 1, 9, 5, 2],
       [9, 2, 3, 9, 5, 5],
       [2, 8, 2, 4, 5, 6]])

In [74]:
arr

array([1, 2, 3, 4])

In [77]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
arr2[0]

array([0., 0., 0., 0.])

In [78]:
arr1

array([[2, 3, 7, 7, 3, 4],
       [7, 7, 9, 1, 1, 1],
       [8, 3, 1, 9, 5, 2],
       [9, 2, 3, 9, 5, 5],
       [2, 8, 2, 4, 5, 6]])

In [81]:
arr1[0,[1,3]]

array([3, 7])

In [83]:
arr1[2:4]

array([[8, 3, 1, 9, 5, 2],
       [9, 2, 3, 9, 5, 5]])

In [82]:
arr1[2:4,[2,3]]

array([[1, 9],
       [3, 9]])

In [84]:
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [85]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 1]])

In [86]:
arr2

array([[1, 1, 1],
       [1, 2, 1],
       [2, 1, 2]])

In [87]:
arr1+arr2

array([[2, 2, 3],
       [3, 3, 3],
       [4, 2, 3]])

In [88]:
arr1-arr2

array([[ 0,  0,  1],
       [ 1, -1,  1],
       [ 0,  0, -1]])

In [89]:
#index wise multi
arr1*arr2

array([[1, 1, 2],
       [2, 2, 2],
       [4, 1, 2]])

In [90]:
#matrix multiplication

In [91]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 1]])

In [92]:
arr2

array([[1, 1, 1],
       [1, 2, 1],
       [2, 1, 2]])

In [93]:
arr1 @ arr2

array([[6, 5, 6],
       [7, 6, 7],
       [5, 5, 5]])

In [94]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 1]])

In [95]:
arr2

array([[1, 1, 1],
       [1, 2, 1],
       [2, 1, 2]])

In [97]:
arr1/arr2 #index wise division

array([[1. , 1. , 2. ],
       [2. , 0.5, 2. ],
       [1. , 1. , 0.5]])

In [98]:
arr1/0

C:\Users\SHIVAM SINGH\AppData\Local\Temp\ipykernel_12544\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [99]:
#Broad casting

In [100]:
arr = np.zeros((3, 4))

In [101]:
arr


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [103]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [110]:
a = np.array([1, 2, 3, 4])

In [111]:
a

array([1, 2, 3, 4])

In [112]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [113]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [121]:
a = np.array([[1, 2, 3]])

In [122]:
a

array([[1, 2, 3]])

In [123]:
a.T

array([[1],
       [2],
       [3]])

In [124]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [125]:
a

array([[1, 2, 3]])

In [126]:
arr + a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [127]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 1]])

In [128]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.41421356],
       [1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.        , 1.        ]])

In [133]:
np.log10(arr1)

array([[0.     , 0.     , 0.30103],
       [0.30103, 0.     , 0.30103],
       [0.30103, 0.     , 0.     ]])

In [130]:
np.exp(arr1)

array([[2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183]])

In [134]:
np.exp(arr1)

array([[2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183]])

In [136]:
a = np.array([1, 2, 3])

In [137]:
a

array([1, 2, 3])

In [138]:
np.min(a)

1

In [139]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 1]])

In [140]:
np.min(arr1)

1

In [141]:
np.max(arr1)

2

In [142]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 1]])

In [143]:
arr1.T

array([[1, 2, 2],
       [1, 1, 1],
       [2, 2, 1]])

In [144]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 1]])

In [145]:
arr1.flatten() #reduce higher dimension to 1 d

array([1, 1, 2, 2, 1, 2, 2, 1, 1])

In [146]:
#expand_dims -->  expands the array by inserting a new axis

In [157]:
arr = np.array([[1, 2, 3], [4, 5, 6], [1,2,3]])

In [158]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [159]:
np.sum(arr)

27

In [160]:
np.sum(arr, axis = 0)

array([ 6,  9, 12])

In [161]:
np.sum(arr, axis = 1)

array([ 6, 15,  6])

In [162]:
#expand_dims >>expand the dimension of array
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [163]:
arr.ndim

1

In [164]:
arr1 = np.expand_dims(arr, axis = 0)
arr1

array([[1, 2, 3, 4]])

In [165]:
arr1.ndim

2

In [166]:
arr2 = np.expand_dims(arr1, axis = 0)
arr2

array([[[1, 2, 3, 4]]])

In [167]:
arr2.shape

(1, 1, 4)

In [168]:
arr

array([1, 2, 3, 4])

In [169]:
arr1 = np.expand_dims(arr, axis = 1)
arr1

array([[1],
       [2],
       [3],
       [4]])

In [170]:
arr = np.zeros((3, 4))

In [171]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [172]:
arr1 = np.expand_dims(arr, axis = 1)
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [173]:
arr1 = np.expand_dims(arr, axis = 0)
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])