In [1]:
import numpy as np

In [5]:
np.__version__

'1.24.3'

In [6]:
l=[1,2,3,4,5]

In [7]:
arr=np.array(l)

In [8]:
type(np.array(l))
##ndarray means :- n dimensional array

numpy.ndarray

In [9]:
arr.ndim

1

In [10]:
l1 = [1, 2, 3, 4, 5, "Rishi"]
arr1 = np.array(l1)
arr1

array(['1', '2', '3', '4', '5', 'Rishi'], dtype='<U11')

In [11]:
arr2=np.array([[1,2,3],[4,5,6]])

In [12]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr2.ndim

2

In [14]:
l2=[1,2,3,4]

In [15]:
mat=np.matrix(l2) #matrix will be by default 2d it cant be 3d

In [16]:
mat

matrix([[1, 2, 3, 4]])

In [17]:
#more ways to convert list into array
np.asarray(l2)

array([1, 2, 3, 4])

In [18]:
np.asanyarray(l2) #Convert the input to an ndarray, but pass ndarray subclasses through.

array([1, 2, 3, 4])

In [19]:
np.asanyarray(mat) #cannot convert matirx into array because matrix is subclass of array

matrix([[1, 2, 3, 4]])

In [20]:
t=([1,2,3],[4,5,6])

In [21]:
np.array(t) #touple into array

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr3=np.array([1,2,3,4,5])

In [23]:
arr3

array([1, 2, 3, 4, 5])

In [24]:
a=arr3

In [25]:
a

array([1, 2, 3, 4, 5])

In [26]:
arr3[0]=1000

In [27]:
arr3

array([1000,    2,    3,    4,    5])

In [28]:
a

array([1000,    2,    3,    4,    5])

In [29]:
b=a.copy()
b[0]=2000

In [30]:
b

array([2000,    2,    3,    4,    5])

In [31]:
a

array([1000,    2,    3,    4,    5])

In [32]:
#multiple ways to generate the array

In [33]:
np.fromfunction(lambda i,j:i==j,shape=(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [34]:
arr

array([1, 2, 3, 4, 5])

In [35]:
arr.shape

(5,)

In [36]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr2.shape

(2, 3)

In [38]:
arr2.size

6

In [39]:
np.fromfunction(lambda i,j:i*j,shape=(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [40]:
for i in range(5):
    print(i)

0
1
2
3
4


In [41]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [42]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [43]:
list(range(5))

[0, 1, 2, 3, 4]

In [44]:
iterable=(i*i for i in range(5))

In [45]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [46]:
np.fromstring("12 34 56",sep=' ')

array([12., 34., 56.])

In [47]:
arr.dtype

dtype('int32')

In [48]:
np.arange(0.1,10.2,0.2)

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,
        2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,
        8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1])

In [49]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [51]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [52]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [55]:
arr4=np.zeros((3,4),int)

In [56]:
arr4

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [57]:
arr4.ndim

2

In [58]:
arr5=np.zeros((3,3,4))

In [60]:
arr5.ndim

3

In [61]:
arr5.shape

(3, 3, 4)

In [62]:
np.ones(4)

array([1., 1., 1., 1.])

In [65]:
arr6=np.ones((2,3))

In [66]:
arr6

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
arr6+5

array([[6., 6., 6.],
       [6., 6., 6.]])